# Generated by Django 6.0 on 2025-12-12 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        ('geo', '0001_initial'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='departments.department'),
        ),
        migrations.AddField(
            model_name='issue',
            name='dept_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='departments.departmenthead'),
        ),
        migrations.AddField(
            model_name='issue',
            name='municipal_corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='geo.municipalcorporation'),
        ),
        migrations.AddField(
            model_name='issue',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='geo.ward'),
        ),
        migrations.AddField(
            model_name='issue',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_issues', to='departments.departmentworker'),
        ),
    ]
