# Generated by Django 6.0 on 2026-01-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('geo', '0004_alter_municipalcorphead_options_and_more'),
        ('issues', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_url',
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='dept_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.departmenthead'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='municipal_corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.municipalcorporation'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('NEEDS_CONFIRMATION', 'NEEDS_CONFIRMATION'), ('ASSIGNED', 'ASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], default='PROCESSING', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.ward'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='workers',
            field=models.ManyToManyField(blank=True, to='departments.departmentworker'),
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('local_image_path', models.TextField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('is_mismatch', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='issues.issue')),
            ],
        ),
    ]
