# Generated by Django 5.2.10 on 2026-03-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_citizen_remove_issue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='issues.issue'),
        ),
    ]
