# Generated by Django 6.0 on 2025-12-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipalcorporation',
            table='municipalcorporation',
        ),
    ]
