# Generated by Django 6.0 on 2025-12-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_municipalcorporation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipalcorphead',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wardhead',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='municipalcorporation',
            table='municipal_corporation',
        ),
    ]
