# Generated by Django 6.0 on 2025-12-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_municipalcorphead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipalcorphead',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wardhead',
            options={'managed': False},
        ),
    ]
